# -*- coding: utf-8 -*-
"""CursoPython_Dia1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9Ll0yswVMyF8NU7jA5TcspWapLLUgNA

# DIA 1

## Temario:
- Tipos de Datos
- Operaciones Matematicas
- Operaciones con String
- Operaciones Logicas
- Operaciones Booleanas

# Tipos de Datos
"""

# Existen los datos:
enteros = 4 # Son numeros sin decimales
flotantes = 3.9 # Son numeros con decimales
type(enteros)

# Caracteres/Strings
caracteres = "a"
cadena_caracteres = "Hello world!"
type(cadena_caracteres)

# Booleanos
falso = False # Falso es 0
verdadero = True # Verdadero es 1
type(falso)

# Imprimir
print(enteros)

"""### Espera, el usuario tambien puede ingresar datos"""

# Con la funcion input, el usuario puede ingresar cualquier tipo de dato
# y podemos guardarlo en cualquier variable
name = input("Mi nombre es: ") # Te lo guarda como string
print(name)

num = input("Ingresa un numero: ")
print(num + 1)

num = int(input("Ingresar numero: "))
print(num + 1)

"""# Operaciones matematicas"""

# 4to Nivel de importancia
# Suma Ordinaria
print("Suma Ordinaria: ")
print(3 + 4)
variable1,variable2 = 20,40
print(variable1 + variable2)

# Resta Ordinaria
print("Resta Ordinaria: ")
print(5 - 2)
# Declaracion de variables
v1 = 10.4
v2 = 15
resultado = v1 - v2
print(resultado)

# 3er Nivel de importancia
# Multiplicacion Ordinaria
print("------------------------------------")
print("Multiplicacion Ordinaria: ")
M1,M2 = 2,3.14
print(M1 * M2)

# Division Ordinaria
print("Division Ordinaria: ")
M1,M2,M3,M4,M5,M6 = 2,5,6,5,4,5
print(M1 / M2)
print(M3 / M4)
print(M5 / M6)

# Division de Piso
print("Division de Piso: ")
print(M1 // M2)
print(M3 // M4)
print(M5 // M6)

# Potencias
print("Potencias: ")
print(2 ** 3) # 8
P1, P2 = 7, 2
print(P1 ** P2) # 49

# Area de un circulo
pi = 3.14
r = 4
A = pi * (r ** 2)
print(A)

"""# Operaciones con String"""

HM = "Hola Mundo"
print(HM)

a,b = "ta","co"
print(a + b)

# Animal, debe tener un nombre, le debe gustar una fruta, debe tener una profesion
Animal = "Tiburon"
Nombre = "Angel"
Fruta = "Mango"
Profesion = "Ingeniero de Software"

print(f"Hola soy {Nombre} y soy un {Animal}, me gusta el {Fruta} y soy {Profesion}")

"""# Operaciones logicas"""

# Empezamos con los operadores logicos <, >, <=, >=, and, or (SIEMPRE RETORNA UN BOOLEANO)
b1 = 4 > 5
b2 = 7 > 3
b3 = 14 > 14
b4 = 14 >= 14

print(b1)
print(b2)
print(b3)
print(b4)

# Quieres un sandwich con todo
pan = True
queso = True
mayonesa = True
lechuga = True
jamon = False
print(pan and queso and mayonesa and lechuga and jamon)

print(True * 20) # True = 1
print(False * 10) # False = 0

"""#"""